// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-1eCHVB1G3K0L4AR8LItROXGxArLzOJA',
    appId: '1:298299187420:web:a2ebd75227593b99591419',
    messagingSenderId: '298299187420',
    projectId: 'todoapp-2929',
    authDomain: 'todoapp-2929.firebaseapp.com',
    storageBucket: 'todoapp-2929.firebasestorage.app',
    measurementId: 'G-2YRC3YWZ3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1tUeyL9WJ0aHqm4iA21izPhJ1cMJgKts',
    appId: '1:298299187420:android:07f0106d45b009ec591419',
    messagingSenderId: '298299187420',
    projectId: 'todoapp-2929',
    storageBucket: 'todoapp-2929.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTzA8igUpDEoHkRHrl9VuwUOX4DWm1qSU',
    appId: '1:298299187420:ios:dece56260db71086591419',
    messagingSenderId: '298299187420',
    projectId: 'todoapp-2929',
    storageBucket: 'todoapp-2929.firebasestorage.app',
    iosBundleId: 'com.example.testApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTzA8igUpDEoHkRHrl9VuwUOX4DWm1qSU',
    appId: '1:298299187420:ios:dece56260db71086591419',
    messagingSenderId: '298299187420',
    projectId: 'todoapp-2929',
    storageBucket: 'todoapp-2929.firebasestorage.app',
    iosBundleId: 'com.example.testApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-1eCHVB1G3K0L4AR8LItROXGxArLzOJA',
    appId: '1:298299187420:web:0858668c61ea152a591419',
    messagingSenderId: '298299187420',
    projectId: 'todoapp-2929',
    authDomain: 'todoapp-2929.firebaseapp.com',
    storageBucket: 'todoapp-2929.firebasestorage.app',
    measurementId: 'G-SB95NESSCE',
  );
}
